services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #     APP_ENV: production
  #     PORT: 8080
  #     DEFAULT_LOCALE: en
  #     MONGODB_URI: mongodb://mongo:27017
  #     MONGODB_DATABASE: media_library
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_go_data:/data/db

volumes:
  mongo_go_data:
